/* empty css                      */import{S as p,A as w,N as v}from"./assets/vendor-D7M8BDcB.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function u(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=u(e);fetch(e.href,t)}})();let f=null,g=null;function h(){const s=window.innerWidth;s<1440&&!f&&(f=new p(".core-swiper",{modules:[w],slidesPerView:1,spaceBetween:16,loop:!0,autoplay:{delay:2500,disableOnInteraction:!1}})),s>=1440&&f&&(f.destroy(!0,!0),f=null),g||(g=new p(".gallery-swiper",{modules:[v,w],slidesPerView:1.1,spaceBetween:16,loop:!0,autoplay:{delay:2500},navigation:{nextEl:".gallery-next",prevEl:".gallery-prev"},breakpoints:{1440:{slidesPerView:4,spaceBetween:24}}}))}h();window.addEventListener("resize",()=>{h()});document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),l=s.querySelector(".icon"),u=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 36V33H42V36H6ZM6 25.5V22.5H42V25.5H6ZM6 15V12H42V15H6Z" fill="#EAF4F7" />
</svg>
    `,o=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#8BDECF" />
</svg>
    `;s.addEventListener("click",()=>{t=!t,l.innerHTML=t?o:c,t?n():i()}),a.forEach(d=>d.addEventListener("click",()=>{i(),l.innerHTML=c,t=!1})),window.addEventListener("scroll",r);function n(){u.style.display="block"}function i(){u.style.display="none"}function r(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function s(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function l(o){const n=document.getElementById(o);if(!n)return;const i=s(),r=n.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(n){const i=this.getAttribute("href");if(!i)return;const[r,d]=i.split("#");if(!d)return;const m=window.location.pathname.split("/").pop();!(r===""||r==="./"||r===m||r==="./"+m)||!document.getElementById(d)||(n.preventDefault(),l(d),t(d))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(i=>i.classList.remove("active"));const n=document.querySelector(`.navigation-item a[href*="#${o}"]`);n&&n.closest(".navigation-item").classList.add("active")}function c(){const o=window.pageYOffset+s()+100;a.forEach(n=>{const i=n.offsetTop,r=i+n.offsetHeight;o>=i&&o<r&&t(n.id)})}if(window.addEventListener("scroll",c),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{l(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
